### ISSUE TITLE
Lesson 12 Stable Coin import error

### ISSUE THREAD

**Issue by PavanTamrakar** [Cyfrin/foundry-defi-stablecoin-f23#21]
![Screenshot (180)](https://github.com/Cyfrin/foundry-defi-stablecoin-f23/assets/72463719/a46f9a36-25f0-4c57-ab63-a3c74ff5bfa8)

I did everything the same showed in the video but was still unable to find the source fill. Can someone help?  @PatrickAlphaC

**Comment by BBashh** [comment]
Hi Pavan,
It looks like there is an error in your _foundry.toml_ file. Make sure your remappings are correct. Use this code:

remappings = ['@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts', '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts']

Hope this helps.

**Comment by Ritik-Agarwal50** [comment]
Ya this a error of a toml file pls re check it

**Comment by PatrickAlphaC** [comment]
looks like this is all set, closing.
