### ISSUE TITLE
Invariant test for redeemCollateral throws Arithmetic overflow/underflow error

### ISSUE THREAD

**Issue by pokhrelanmol** [Cyfrin/foundry-defi-stablecoin-f23#30]
While running the test using ```forge test -m invariant_protocolMustHaveMoreValueThatTotalSupplyDollars```. The Arithmetic overflow/underflow error appears.

![image](https://github.com/Cyfrin/foundry-defi-stablecoin-f23/assets/75737628/ce2f5b99-f557-4345-9587-b1c476de4ba6)

**Comment by PatrickAlphaC** [comment]
Yep! This is something we are aware of... We need to update the handler to be better at filtering this out.

**Comment by pokhrelanmol** [comment]
Ohooo! Do we need to check if the caller of redeemCollateral has already deposited the fund or not?  I tried this easy fix  by pranking the msg.sender and surprisingly all tests are passing now but I think I'm missing something here 

![image](https://github.com/Cyfrin/foundry-defi-stablecoin-f23/assets/75737628/0c46acd0-9c92-4a04-be2b-d885970970f8)

**Comment by Praveen2645** [comment]
![Screenshot from 2023-09-15 14-10-17](https://github.com/Cyfrin/foundry-defi-stablecoin-f23/assets/107745548/9c9a805c-7b38-453e-8e0f-a6febe7c2dcd)


got errors in redeemCollateral Tests

**Comment by dhanesh24g** [comment]
> Ohooo! Do we need to check if the caller of redeemCollateral has already deposited the fund or not? I tried this easy fix by pranking the msg.sender and surprisingly all tests are passing now but I think I'm missing something here
> 
> ![image](https://private-user-images.githubusercontent.com/75737628/253748444-0c46acd0-9c92-4a04-be2b-d885970970f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NDA2NzIsIm5iZiI6MTcwNjQ0MDM3MiwicGF0aCI6Ii83NTczNzYyOC8yNTM3NDg0NDQtMGM0NmFjZDAtOWM5Mi00YTA0LWJlMmItZDg4NTk3MDk3MGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDExMTI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyNDJlZTM1ZTE1NDE0NmI5NmVjOWZlYTcxNDRlMjY1MjQxOWNlMDgwNzU5MjU2OWVkZTRlYmViNDgzYTIwMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6gY2T0yL0G_0TopZKVJ8YnDDfT8f60vFnCdf_ZCNuq8)

Yes, while redeeming the collateral, we should prank msg.sender as it is includes transferring the amount from DSCEngine to the sender's account.

**Comment by 4rdii** [comment]
Is there any new answer to this issue? I've been running the test a few times and using console .log in the Engine smart contract like below:
 `function _redeemCollateral(
        address tokenCollateralAddress,
        uint256 amountCollateral,
        address from,
        address to
    ) private {
        console.log(
            "deposited",
            s_collateralDeposited[from][tokenCollateralAddress]
        );
        console.log("redeem amount", amountCollateral);

        s_collateralDeposited[from][tokenCollateralAddress] -= amountCollateral;

        emit CollateralRedeemed(
            from,
            to,
            tokenCollateralAddress,
            amountCollateral
        );
        bool success = IERC20(tokenCollateralAddress).transfer(
            to,
            amountCollateral
        );

        if (!success) {
            revert DSCEngine__TransferFailed();
        }
    }`
I get this response in console when the test fails:
 `  deposited 0
  redeem amount 61114769189951327882389361110`
Does this mean that the mapping sometimes doesn't store the correct value? I'm not really sure why.
Also if anyone wants further information I have some other logs which are from the handler function: 
`   function redeemCollateral(
        uint256 collateralSeed,
        uint256 amountCollateral,
        uint256 addressSeed
    ) public {
      // just testing to see if senders with collateral fixes the problem which it didn't :)
        if (usersWithCollateralDeposited.length == 0) {
            return;
        }
        address sender = usersWithCollateralDeposited[
            addressSeed % usersWithCollateralDeposited.length
        ];
        ERC20Mock collateral = _getCollateralFromSeed(collateralSeed);
        uint256 maxCollateralToRedeem = dsce.getAccountCollateralAmount(
            msg.sender,
            address(collateral)
        ); // parameters should change position didint change for now because of the video
        amountCollateral = bound(amountCollateral, 0, maxCollateralToRedeem);
        if (amountCollateral == 0) {
            return;
        }
        console.log("collateral address", address(collateral));
        console.log("amountCollateral", amountCollateral);
        console.log("maxCollateralToRedeem", maxCollateralToRedeem);
        console.log("wethsupplyofdsce", collateral.balanceOf(address(dsce)));
        console.log("Healthfactor", dsce.getHealthFactor(msg.sender));
        console.log("Minted amount", dsc.balanceOf(msg.sender));
        console.log("diffrense", maxCollateralToRedeem - amountCollateral);
        dsce.redeemCollateral(address(collateral), amountCollateral);
    }`
and these are the logs when we fail 
`collateral address 0xBb2180ebd78ce97360503434eD37fcf4a1Df61c3
  amountCollateral 61114769189951327882389361110
  maxCollateralToRedeem 79228162514264337593543950334
  wethsupplyofdsce 246149140633768714826038757345
  Healthfactor 1000000000000000000
  Minted amount 79228162514264337593543950334000
  diffrense 18113393324313009711154589224`

**Comment by PatrickAlphaC** [comment]
Fixed here!

https://github.com/Cyfrin/foundry-defi-stablecoin-f23/commit/593448729372022572d83e769f2b18c83fc9b455
