### ISSUE TITLE
issue with console.log 

### ISSUE THREAD

**Issue by Frankcastleauditor** [Cyfrin/foundry-defi-stablecoin-f23#31]
i have a problem with the console.log which all the logs are appear in hexadecimal form not the hex or decimals 

![Screenshot from 2023-07-14 00-55-45](https://github.com/Cyfrin/foundry-defi-stablecoin-f23/assets/134559450/14a3ad36-187e-41a9-b122-e3906507c9dc)
![Screenshot from 2023-07-14 00-55-45](https://github.com/Cyfrin/foundry-defi-stablecoin-f23/assets/134559450/70a33299-3843-4256-b853-654c162f927b)

**Comment by PatrickAlphaC** [comment]
Thanks! Thats just how foundry outputs them at the moment.
