### ISSUE TITLE
Missing Video

### ISSUE THREAD

**Issue by Haftob** [Cyfrin/foundry-defi-stablecoin-f23#57]
There's a video missing in the Advanced Foundry Section 3: Develop a DeFi Protocol. There's no video for  **"Create the fuzz tests handler pt.2".**
Although Video 19  was named "Create the fuzz tests handler pt.2" but that was actually for pt.1 of invariant testing (i.e. OpenInvariants Tests). I think the problem was from a miss up along the line on naming the videos.
Pls Check. Thanks & Regards.

**Comment by PatrickAlphaC** [comment]
Cc @cromewar

**Comment by cromewar** [comment]
Already solved
