### ISSUE TITLE
Reentracyguard is now in utils

### ISSUE THREAD

**Issue by S23Web3** [Cyfrin/foundry-defi-stablecoin-f23#59]
Hi
Reentrancy guard moved (I put it without remapping below) in the new openzeppelin 5.0
from
`import {ReentrancyGuard} from "lib/openzeppelin-contracts/security/utils/ReentrancyGuard.sol";`
to
`import {ReentrancyGuard} from "lib/openzeppelin-contracts/contracts/utils/ReentrancyGuard.sol";`
in the DSCEngine.sol i

**Comment by PatrickAlphaC** [comment]
ah, thanks. Any chance you can open a PR for this?

**Comment by PatrickAlphaC** [comment]
Ah, actually, looks like this is in a newer version of openzeppelin contracts. I'd like to keep the versions here, so I'm closing this.

**Comment by S23Web3** [comment]
Aha, thanks makes sense. is there a way in the make to download only the
relevant version? Then again, on every lesson when the OZ is installed or
make install is executed it needs to be updated.
I believe that you recommend 4.6

**Comment by PatrickAlphaC** [comment]
Good idea! Yes! Can you see the Updraft github? 

https://github.com/Cyfrin/Updraft/tree/dev

Could you make a PR?

**Comment by S23Web3** [comment]
Could you explain what you mean to do with the PR so I can execute it?
I see the updraft, am enlisted and at the s&a part of the course.

**Comment by S23Web3** [comment]
It mentions that I need to be a collab, or should I write ever comments and
tags in one issue?

**Comment by PatrickAlphaC** [comment]
Ah sorry, a "PR" is a "Pull Request".
