### ISSUE TITLE
Mock contracts pragma needs to be updated with the ^ SIGN

### ISSUE THREAD

**Issue by S23Web3** [Cyfrin/foundry-defi-stablecoin-f23#61]
Most of the mocks have 
pragma solidity 0.8.xx;

This will not work and give errors, it needs to be updated at least with the ^ sign
pragma solidity ^0.8.xx;

`
Error: 
Found incompatible Solidity versions:

test/mocks/MockFailedTransfer.sol (0.8.19) imports:

    lib/openzeppelin-contracts/contracts/token/ERC20/extensions/ERC20Burnable.sol (^0.8.20)
    lib/openzeppelin-contracts/contracts/access/Ownable.sol (^0.8.18)
    lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol (^0.8.18)
    lib/openzeppelin-contracts/contracts/utils/Context.sol (^0.8.20)
    lib/openzeppelin-contracts/contracts/utils/Context.sol (^0.8.20)
    lib/openzeppelin-contracts/contracts/token/ERC20/IERC20.sol (^0.8.20)
    lib/openzeppelin-contracts/contracts/token/ERC20/extensions/IERC20Metadata.sol (^0.8.20)
    lib/openzeppelin-contracts/contracts/utils/Context.sol (^0.8.20)
    lib/openzeppelin-contracts/contracts/interfaces/draft-IERC6093.sol (^0.8.20)
    lib/openzeppelin-contracts/contracts/token/ERC20/IERC20.sol (^0.8.20)
`

**Comment by PatrickAlphaC** [comment]
You might be installing the wrong imports! Can you please follow the instructions in the README? There are specific dependencies you'll need to install.

**Comment by S23Web3** [comment]
Thank you, indeed I was.
