### ISSUE TITLE
Execution reverted when I run cast send

### ISSUE THREAD

**Issue by nthang2** [Cyfrin/foundry-defi-stablecoin-f23#69]
This is my request: 
cast send 0xf16b3e8E4F8F64716a05D0Da8366b6e56D670CE2 "depositCollateralAndMintDSC(address, uint256, uint256)" 0xD4348969bED34f4218F12aEbE91173fC3A7Dd6E7 1000 1000 --rpc-url $SEPOLIA_RPC_URL --private-key $PRIVATE_KEY
But it's error. I can not send the transaction. 
Error: (code: -32000, message: execution reverted, data: None)

Can you explain about why ? and what is ERC20 token address should I pass ? And what address destination should I pass ? 
Thanks

**Comment by EngrPips** [comment]
Hello @nthang2 , you should use the `discussion` tab to question relating to your code not working correctly as this `issues` tab is for reporting issues that you found with the codebase.

**Comment by nthang2** [comment]
Thanks

**Comment by EngrPips** [comment]
Anytime
