### ISSUE TITLE
Update Config to Use the Latest Open Zeppelin ERC20Mock

### ISSUE THREAD

**Issue by K-G-J** [Cyfrin/foundry-defi-stablecoin-f23#7]
Hello,
I noticed you were using an older version of the ERC20Mock in your HelperConfig.s.sol script. The [version you are using](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/0a25c1940ca220686588c4af3ec526f725fe2582/contracts/mocks/ERC20Mock.sol) seems to be updated 2 years ago (6/7/2021). The [latest ERC20Mock](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/mocks/token/ERC20Mock.sol) as of the update on 5/29/2023 requires no constructor arguments. You may want to change the config script to keep up to date and so people don't run into issues was installing the latest Open Zeppelin contracts lib.

**Comment by PatrickAlphaC** [comment]
hmmmmmmmm. Thank you! Looks like I wrote the code before this update rolled in...

If they follow along with the video and choose the version I use this should be fine. Going to close this for now, but let's see how many people run into this issue.
